In [19]:
import requests
from bs4 import BeautifulSoup

In [20]:

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://www.google.com/",

}

response = requests.get("https://news.err.ee/", headers=headers)
doc = BeautifulSoup(response.text)

In [21]:
print(response.status_code)

200

In [22]:
# What is the selector for the headlines WITH THE LINKS?
# Works from right to left
# a meana <a> tag
# .c_t means something with the class "c_t"
# (space) means "inside of"
# so this means links inside of the class c_t
links = doc.select(".news-article")
len(links)

20

In [23]:
print (links[2])

<h2 class="news-article"><a aria-label="Reform and Eesti 200 recieve lowest party donations in Q2" href="https://news.err.ee/1610075701/reform-and-eesti-200-recieve-lowest-party-donations-in-q2">Reform and Eesti 200 recieve lowest party donations in Q2</a></h2>

In [24]:
# We love a good CSV file
# we probably want one with a HEADLINE column
# and also a URL column

# to make a CSV we need a LIST of DICTIONARIES
for link in links:
    print("----")
    # Print out the text
    #print(link.text)
    # Print out the URL it points to
    # <a href="blahblah.html" title="...">
    # <img src="....">    
    #print(link['href'])
    a = link.find("a")
    print(a.text)
    print(a['href'])

----
MP: Estonia loses a 'good friend' with US Senator Lindsey Graham's death
https://news.err.ee/1610075755/mp-estonia-loses-a-good-friend-with-us-senator-lindsey-graham-s-death
----
Airport tramline on schedule to reopen on August 1 after test run
https://news.err.ee/1610075713/airport-tramline-on-schedule-to-reopen-on-august-1-after-test-run
----
Reform and Eesti 200 recieve lowest party donations in Q2
https://news.err.ee/1610075701/reform-and-eesti-200-recieve-lowest-party-donations-in-q2
----
Producers do not plan to stop selling cage-free eggs anytime soon
https://news.err.ee/1610075698/producers-do-not-plan-to-stop-selling-cage-free-eggs-anytime-soon
----
Russian disinformation surge may be connected to upcoming Baltic elections
https://news.err.ee/1610075686/russian-disinformation-surge-may-be-connected-to-upcoming-baltic-elections
----
Estonia falls just short against Ireland in European golf team final
https://news.err.ee/1610075257/estonia-falls-just-short-against-ireland-in-european-golf-team-final
----
New Estonian state fleet vessel runs on Saaremaa cow manure
https://news.err.ee/1610075344/new-estonian-state-fleet-vessel-runs-on-saaremaa-cow-manure
----
Saaremaa's I Land Sound summer festival program announced
https://news.err.ee/1610075317/saaremaa-s-i-land-sound-summer-festival-program-announced
----
Pärnu Music Festival opens with world premieres and international stars
https://news.err.ee/1610075284/parnu-music-festival-opens-with-world-premieres-and-international-stars
----
3 minors assaulted by adults in Pärnu, criminal investigation launched
https://news.err.ee/1610074756/3-minors-assaulted-by-adults-in-parnu-criminal-investigation-launched
----
Defense Intelligence: Russia may face air force fuel problems after Ukrainian strikes
https://news.err.ee/1610074699/defense-intelligence-russia-may-face-air-force-fuel-problems-after-ukrainian-strikes
----
Pedestrian killed after Tallinn tram driver used phone on duty
https://news.err.ee/1610074585/pedestrian-killed-after-tallinn-tram-driver-used-phone-on-duty
----
ERR carrying FIFA World Cup 2026 knockout matches live
https://news.err.ee/1610042176/err-carrying-fifa-world-cup-2026-knockout-matches-live
----
Estonian government approves extending temporary protection of Ukrainian refugees
https://news.err.ee/1610073646/estonian-government-approves-extending-temporary-protection-of-ukrainian-refugees
----
Where to watch the climax of the FIFA world cup
https://news.err.ee/1610073649/where-to-watch-the-climax-of-the-fifa-world-cup
----
Airport tramline on schedule to reopen on August 1 after test run
https://news.err.ee/1610075713/airport-tramline-on-schedule-to-reopen-on-august-1-after-test-run
----
Estonia joins other 2 Baltic states in protest over Russian airspace claims
https://news.err.ee/1610075275/estonia-joins-other-2-baltic-states-in-protest-over-russian-airspace-claims
----
3 minors assaulted by adults in Pärnu, criminal investigation launched
https://news.err.ee/1610074756/3-minors-assaulted-by-adults-in-parnu-criminal-investigation-launched
----
Estonia's 'Night Fairies' help keep Beach Grind festival-goers safe
https://news.err.ee/1610075200/estonia-s-night-fairies-help-keep-beach-grind-festival-goers-safe
----
Producers do not plan to stop selling cage-free eggs anytime soon
https://news.err.ee/1610075698/producers-do-not-plan-to-stop-selling-cage-free-eggs-anytime-soon

In [25]:
# We love a good CSV file
# we probably want one with a HEADLINE column
# and also a URL column

# to make a CSV we need a LIST of DICTIONARIES
# YOUR MISSION:
# 1. Make an empty list called all_data
# 2. Add our data dictionary to it each time we loop
# 3. Look at the list
all_data = []
for link in links:
    # print("----")
    a = link.find("a")
    data = {
        'url': a['href'],
        'headline': a.text
    }
    # print(data)
    all_data.append(data)
all_data

[{'url': 'https://news.err.ee/1610075755/mp-estonia-loses-a-good-friend-with-us-senator-lindsey-graham-s-death',
  'headline': "MP: Estonia loses a 'good friend' with US Senator Lindsey Graham's death"},
 {'url': 'https://news.err.ee/1610075713/airport-tramline-on-schedule-to-reopen-on-august-1-after-test-run',
  'headline': 'Airport tramline on schedule to reopen on August 1 after test run'},
 {'url': 'https://news.err.ee/1610075701/reform-and-eesti-200-recieve-lowest-party-donations-in-q2',
  'headline': 'Reform and Eesti 200 recieve lowest party donations in Q2'},
 {'url': 'https://news.err.ee/1610075698/producers-do-not-plan-to-stop-selling-cage-free-eggs-anytime-soon',
  'headline': 'Producers do not plan to stop selling cage-free eggs anytime soon'},
 {'url': 'https://news.err.ee/1610075686/russian-disinformation-surge-may-be-connected-to-upcoming-baltic-elections',
  'headline': 'Russian disinformation surge may be connected to upcoming Baltic elections'},
 {'url': 'https://news.err.ee/1610075257/estonia-falls-just-short-against-ireland-in-european-golf-team-final',
  'headline': 'Estonia falls just short against Ireland in European golf team final'},
 {'url': 'https://news.err.ee/1610075344/new-estonian-state-fleet-vessel-runs-on-saaremaa-cow-manure',
  'headline': 'New Estonian state fleet vessel runs on Saaremaa cow manure'},
 {'url': 'https://news.err.ee/1610075317/saaremaa-s-i-land-sound-summer-festival-program-announced',
  'headline': "Saaremaa's I Land Sound summer festival program announced"},
 {'url': 'https://news.err.ee/1610075284/parnu-music-festival-opens-with-world-premieres-and-international-stars',
  'headline': 'Pärnu Music Festival opens with world premieres and international stars'},
 {'url': 'https://news.err.ee/1610074756/3-minors-assaulted-by-adults-in-parnu-criminal-investigation-launched',
  'headline': '3 minors assaulted by adults in Pärnu, criminal investigation launched'},
 {'url': 'https://news.err.ee/1610074699/defense-intelligence-russia-may-face-air-force-fuel-problems-after-ukrainian-strikes',
  'headline': 'Defense Intelligence: Russia may face air force fuel problems after Ukrainian strikes'},
 {'url': 'https://news.err.ee/1610074585/pedestrian-killed-after-tallinn-tram-driver-used-phone-on-duty',
  'headline': 'Pedestrian killed after Tallinn tram driver used phone on duty'},
 {'url': 'https://news.err.ee/1610042176/err-carrying-fifa-world-cup-2026-knockout-matches-live',
  'headline': 'ERR carrying FIFA World Cup 2026 knockout matches live'},
 {'url': 'https://news.err.ee/1610073646/estonian-government-approves-extending-temporary-protection-of-ukrainian-refugees',
  'headline': 'Estonian government approves extending temporary protection of Ukrainian refugees'},
 {'url': 'https://news.err.ee/1610073649/where-to-watch-the-climax-of-the-fifa-world-cup',
  'headline': 'Where to watch the climax of the FIFA world cup'},
 {'url': 'https://news.err.ee/1610075713/airport-tramline-on-schedule-to-reopen-on-august-1-after-test-run',
  'headline': 'Airport tramline on schedule to reopen on August 1 after test run'},
 {'url': 'https://news.err.ee/1610075275/estonia-joins-other-2-baltic-states-in-protest-over-russian-airspace-claims',
  'headline': 'Estonia joins other 2 Baltic states in protest over Russian airspace claims'},
 {'url': 'https://news.err.ee/1610074756/3-minors-assaulted-by-adults-in-parnu-criminal-investigation-launched',
  'headline': '3 minors assaulted by adults in Pärnu, criminal investigation launched'},
 {'url': 'https://news.err.ee/1610075200/estonia-s-night-fairies-help-keep-beach-grind-festival-goers-safe',
  'headline': "Estonia's 'Night Fairies' help keep Beach Grind festival-goers safe"},
 {'url': 'https://news.err.ee/1610075698/producers-do-not-plan-to-stop-selling-cage-free-eggs-anytime-soon',
  'headline': 'Producers do not plan to stop selling cage-free eggs anytime soon'}]

In [26]:
import pandas as pd

# Just feed the list of dictionaries to pandas
# and it makes us a nice beautiful dataframe
df = pd.DataFrame(all_data)
df.head()

,url,headline
0,https://news.err.ee/1610075755/mp-estonia-lose...,MP: Estonia loses a 'good friend' with US Sena...
1,https://news.err.ee/1610075713/airport-tramlin...,Airport tramline on schedule to reopen on Augu...
2,https://news.err.ee/1610075701/reform-and-eest...,Reform and Eesti 200 recieve lowest party dona...
3,https://news.err.ee/1610075698/producers-do-no...,Producers do not plan to stop selling cage-fre...
4,https://news.err.ee/1610075686/russian-disinfo...,Russian disinformation surge may be connected ...

In [27]:
import os

# Try to create a folder called 'data'
# and if it exists DON'T THROW AN ERROR
os.makedirs("data\err_ee", exist_ok=True)

<>:5: SyntaxWarning: "\e" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\e"? A raw string is also an option.
<>:5: SyntaxWarning: "\e" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\e"? A raw string is also an option.
C:\Users\jpjul\AppData\Local\Temp\ipykernel_11316\771705377.py:5: SyntaxWarning: "\e" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\e"? A raw string is also an option.
  os.makedirs("data\err_ee", exist_ok=True)

In [28]:
from datetime import datetime

# This would keep track down to the second
datetime.now().strftime("%Y-%m-%d_%H.%M.%S")

# This only does the day
date_string = datetime.now().strftime("%Y-%m-%d_%H.%M.%S")
filepath = f"data/err_ee/{date_string}.csv"

df.to_csv(filepath, index=False)

In [29]:
# Append to an always-updated file, deduplicated by url.

# add columns for when we scraped this
df['scrape_date'] = datetime.now().strftime("%Y-%m-%d")
df['scrape_datetime'] = datetime.now().strftime("%Y-%m-%d_%H.%M.%S")

# open the always-updated file if it exists, else start blank
try:
    existing_df = pd.read_csv("err_ee-always-updated.csv")
except:
    existing_df = pd.DataFrame([])

# OLD first, then NEW, so keep='first' preserves the earliest scrape date
combined = pd.concat([existing_df, df], ignore_index=True)
print("Before dropping duplicates:", len(combined))

# dedup on url ONLY -> only genuinely new articles get added to the file
combined = combined.drop_duplicates(subset=['url'], keep='first')
print("After dropping duplicates: ", len(combined))

combined.to_csv("err_ee-always-updated.csv", index=False)
combined.head()

Before dropping duplicates: 20
After dropping duplicates:  17

,url,headline,scrape_date,scrape_datetime
0,https://news.err.ee/1610075755/mp-estonia-lose...,MP: Estonia loses a 'good friend' with US Sena...,2026-07-12,2026-07-12_21.48.16
1,https://news.err.ee/1610075713/airport-tramlin...,Airport tramline on schedule to reopen on Augu...,2026-07-12,2026-07-12_21.48.16
2,https://news.err.ee/1610075701/reform-and-eest...,Reform and Eesti 200 recieve lowest party dona...,2026-07-12,2026-07-12_21.48.16
3,https://news.err.ee/1610075698/producers-do-no...,Producers do not plan to stop selling cage-fre...,2026-07-12,2026-07-12_21.48.16
4,https://news.err.ee/1610075686/russian-disinfo...,Russian disinformation surge may be connected ...,2026-07-12,2026-07-12_21.48.16